In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

from pathlib import Path
import glob

import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

In [23]:
def estandarizar_he (ruta, mes, periodo):
    df = pd.read_excel(ruta, sheet_name=mes, header=1)
    df1 = df[["SEDE", "SEC", "DNI", "PUESTO", "CONDICION", 'SALDO DEL PERIODO', 'TOTAL COMPENSACION', 'HE DEL PERIODO + SALDO INICIAL', 'TOTAL HORAS A PAGAR']]
    df1["PERIODO"] = periodo
    display(df1.head(1))
    return df1

In [25]:
ruta = r"data_he\Liquidación de Asistencia ABRIL 2025.xls"
mes = "ABRIL"
periodo = "202504"

df04 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,SPO PVO HUANUCO,ALMACÉN FRESCOS,73104317,SPO REPRES. DE SERVICIOS I,EMPLEADO,0.733333,0.0,0.733333,0.0,202504

In [26]:
ruta = r"data_he\Liquidación de Asistencia AGOSTO 2025.xls"
mes = "AGOSTO"
periodo = "202508"

df08 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA LA MOLINA,CAJAS,71455580,CFR CAJERO 5X2,PART TIME,0.0,0.0,0.0,0.0,202508

In [27]:
ruta = r"data_he\Liquidación de Asistencia DICIEMBRE 2025.xls"
mes = "DICIEMBRE"
periodo = "202512"

df12 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA CHOSICA,ALMACÉN FRESCOS,72232431,CFR REPRES. DE SERVICIOS,EMPLEADO,16.283333,0.0,0.0,0.0,202512

In [28]:
ruta = r"data_he\Liquidación de Asistencia ENERO 2025.xls"
mes = "ENERO"
periodo = "202501"

df01 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,SPO PVO HUANUCO,ALMACÉN,77336057,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.0,0.0,0.0,0.0,202501

In [29]:
ruta = r"data_he\Liquidación de Asistencia FEBRERO 2025.xls"
mes = "FEBRERO"
periodo = "202502"

df02 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA EL CHACARERO,CAJAS,46839889,CFR CAJERO 6X1,PART TIME,0.0,0.0,0.0,0.0,202502

In [30]:
ruta = r"data_he\Liquidación de Asistencia JULIO 2025.xls"
mes = "JULIO"
periodo = "202507"

df07 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA PUENTE PIEDRA,ALMACÉN,77977710,CFR REPRES. DE SERVICIOS 5X2 2DO TURNO,PART TIME,0.0,0.0,0.0,0.0,202507

In [31]:
ruta = r"data_he\Liquidación de Asistencia JUNIO 2025.xls"
mes = "JUNIO"
periodo = "202506"

df06 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA TALARA,ALMACÉN FRESCOS,75604797,CFR REPRES. DE SERVICIOS 2DO TURNO,PART TIME,0.0,0.0,0.0,0.0,202506

In [32]:
ruta = r"data_he\Liquidación de Asistencia MARZO 2025.xls"
mes = "MARZO"
periodo = "202503"

df03 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA RIMAC,SALA,48404362,CFR REPRES. DE SERVICIOS,EMPLEADO,1.75,0.0,1.75,0.516667,202503

In [33]:
ruta = r"data_he\Liquidación de Asistencia MAYO 2025.xls"
mes = "MAYO"
periodo = "202505"

df05 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA ALFONSO UGARTE,SALA,6781124,CFR REPRES. DE SERVICIOS EO,EMPLEADO,0.666667,1.083333,0.0,0.0,202505

In [34]:
ruta = r"data_he\Liquidación de Asistencia NOVIEMBRE 2025.xls"
mes = "NOVIEMBRE"
periodo = "202511"

df11 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA CHICLAYO,SALA,76059699,CFR REPRES. DE SERVICIOS 5X2 2DO TURNO,PART TIME,0.0,0.0,0.0,0.0,202511

In [35]:
ruta = r"data_he\Liquidación de Asistencia OCTUBRE 2025.xls"
mes = "OCTUBRE"
periodo = "202510"

df10 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA SJ LURIGANCHO,ELECTRO,42004285,CFR VENDEDOR,EMPLEADO,1.683333,0.0,1.683333,0.0,202510

In [37]:
ruta = r"data_he\Liquidación de Asistencia SETIEMBRE 2025.xls"
mes = "SETIEMBRE"
periodo = "202509"

df09 = estandarizar_he (ruta, mes, periodo)

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA SAN ISIDRO,E-COMMERCE VIRTUAL,73117349,CFR REPRES. DE SERVICIOS 2DO TURNO,PART TIME,0.0,0.0,0.0,0.0,202509

In [40]:
ruta = r"C:\Users\eparedes\Documents\SPSA\05_ProyectoCAPO\data_he\Liquidación de Asistencia - 1Q.xlsx"


dfx = pd.read_excel(ruta, sheet_name="CONSOLIDADO", header=1)

In [44]:
dfx["MES"].unique()

dicc = {"ENERO":"202601", "FEBRERO":"202602", "MARZO":"202603"}

In [45]:
dfx["PERIODO"] = dfx["MES"].map(dicc)

In [48]:
dfx

dfxy = dfx[["SEDE", "SEC", "DNI", "PUESTO", "CONDICION", 'SALDO DEL PERIODO', 'TOTAL COMPENSACION', 'HE DEL PERIODO + SALDO INICIAL', 'TOTAL HORAS A PAGAR', 'PERIODO']]
dfxy

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,CFR PVEA IZAGUIRRE,SALA,7164899,CFR REPRESENTANTE DE SERVICIO 5X2 D,PART TIME,0.000000,0.000000,0.000000,0.000000,202601
1,CFR PVEA UNIVERSITARIA,CAJAS,7220394,CFR REPRES. DE SERVICIOS 5X2 EO,PART TIME,0.000000,0.000000,0.000000,0.000000,202601
2,CFR PVEA MIRAFLORES,CAJAS,7247818,CFR MULTIFUNCIONAL EO,EMPLEADO,6.650000,0.000000,4.916667,0.000000,202601
3,CFR PVEA SALAVERRY,CAJAS,7249185,CFR REPRES. DE SERVICIOS 5X2,PART TIME,0.000000,0.000000,0.000000,0.000000,202601
4,CFR PVEA BREÑA CENTENARIO,SALA,7251805,CFR REPRES. DE SERVICIOS I,EMPLEADO,10.283333,2.500000,10.283333,6.866667,202601
...,...,...,...,...,...,...,...,...,...,...
68811,CFR PVEA CHICLAYO,PASTELERÍA,80510068,CFR REPRES. DE SERVICIOS,EMPLEADO,0.000000,0.000000,0.000000,0.000000,202603
68812,CFR PVEA CENTRO CIVICO,CAJAS,80575112,CFR REPRESENTANTE DE SERVICIO 5X2 D,PART TIME,0.000000,0.000000,0.000000,0.000000,202603
68813,CFR PVEA LA CURVA,CAJAS,80607695,CFR CAJERO 5X2,PART TIME,1.533333,0.000000,1.533333,0.000000,202603
68814,CFR PVEA CHIMBOTE,CAJAS,80608408,CFR CAJERO 3X4,PART TIME,0.000000,0.000000,0.000000,0.000000,202603
68815,CFR SVEA SALAMANCA,SALA,80615260,CFR REPRES. DE SERVICIOS,EMPLEADO,4.600000,5.466667,0.000000,0.000000,202603

In [49]:
dff = pd.concat([df01, df02, df03, df04, df05, df06, df07, df08, df09, df10, df11, df12, dfxy])

In [68]:
dff

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,SPO PVO HUANUCO,ALMACÉN,77336057,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
1,SPO PVO HUANUCO,ALMACÉN,71688899,SPO MULTIFUNCIONAL PEAK CAMPAÑA,EMPLEADO,0.000000,0.000000,0.000000,0.0,202501
2,SPO PVO HUANUCO,ALMACÉN,75928476,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
3,SPO PVO HUANUCO,SALA,74427670,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
4,SPO PVO HUANUCO,SALA,72887123,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
...,...,...,...,...,...,...,...,...,...,...
68811,CFR PVEA CHICLAYO,PASTELERÍA,80510068,CFR REPRES. DE SERVICIOS,EMPLEADO,0.000000,0.000000,0.000000,0.0,202603
68812,CFR PVEA CENTRO CIVICO,CAJAS,80575112,CFR REPRESENTANTE DE SERVICIO 5X2 D,PART TIME,0.000000,0.000000,0.000000,0.0,202603
68813,CFR PVEA LA CURVA,CAJAS,80607695,CFR CAJERO 5X2,PART TIME,1.533333,0.000000,1.533333,0.0,202603
68814,CFR PVEA CHIMBOTE,CAJAS,80608408,CFR CAJERO 3X4,PART TIME,0.000000,0.000000,0.000000,0.0,202603
68815,CFR SVEA SALAMANCA,SALA,80615260,CFR REPRES. DE SERVICIOS,EMPLEADO,4.600000,5.466667,0.000000,0.0,202603

In [56]:
df_dic = pd.read_excel("diccionario_locales.xlsx")

In [59]:
dff1 = dff.merge(df_dic[["SEDE", "codigo_local"]], on="SEDE", how="left")

In [61]:
dff1["AÑO"] = dff1["PERIODO"].str[0:4]

In [64]:
dff1[dff1["PERIODO"].isin(["202501", "202502", "202503", "202504", "202601", "202602", "202603", "202604"])].groupby(["codigo_local", "AÑO"])["TOTAL HORAS A PAGAR"].sum().reset_index()

    codigo_local   AÑO  TOTAL HORAS A PAGAR
0           1198  2025            33.233333
1           1198  2026            88.000000
2           1593  2025          1028.283333
3           1593  2026           531.633333
4           1199  2025           634.683333
..           ...   ...                  ...
219         V290  2026           312.566667
220         X209  2025            24.600000
221         X209  2026           164.433333
222         X210  2025            77.783333
223         X210  2026            95.466667

[224 rows x 3 columns]

In [ ]:
dff2 = dff1[dff1["PERIODO"].isin(["202501", "202502", "202503", "202601", "202602", "202603"])].pivot_table(index="codigo_local",
    columns="AÑO",
    values="TOTAL HORAS A PAGAR",
    aggfunc="sum",  # Evita duplicidad si hay múltiples registros
).reset_index()

In [67]:
dff2.to_excel("he.xlsx", index=False)

In [71]:
dff1[dff1["CONDICION"].isnull()]

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO,codigo_local,AÑO
2981,CFR PVEA PIURA,NaN,SCHEDULERPRUEBA,CFR CAJERO 6X1,NaN,0.0,0.0,0.0,0.0,202501,P145,2025
9729,CFR PVEA COMAS,NaN,49064989,CFR REPRES. DE SERVICIOS 2DO TURNO EXTRAORDINARIO,NaN,0.0,0.0,0.0,0.0,202501,P084,2025

In [73]:
dff

,SEDE,SEC,DNI,PUESTO,CONDICION,SALDO DEL PERIODO,TOTAL COMPENSACION,HE DEL PERIODO + SALDO INICIAL,TOTAL HORAS A PAGAR,PERIODO
0,SPO PVO HUANUCO,ALMACÉN,77336057,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
1,SPO PVO HUANUCO,ALMACÉN,71688899,SPO MULTIFUNCIONAL PEAK CAMPAÑA,EMPLEADO,0.000000,0.000000,0.000000,0.0,202501
2,SPO PVO HUANUCO,ALMACÉN,75928476,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
3,SPO PVO HUANUCO,SALA,74427670,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
4,SPO PVO HUANUCO,SALA,72887123,SPO MULTIFUNCIONAL PEAK CAMPAÑA,PART TIME,0.000000,0.000000,0.000000,0.0,202501
...,...,...,...,...,...,...,...,...,...,...
68811,CFR PVEA CHICLAYO,PASTELERÍA,80510068,CFR REPRES. DE SERVICIOS,EMPLEADO,0.000000,0.000000,0.000000,0.0,202603
68812,CFR PVEA CENTRO CIVICO,CAJAS,80575112,CFR REPRESENTANTE DE SERVICIO 5X2 D,PART TIME,0.000000,0.000000,0.000000,0.0,202603
68813,CFR PVEA LA CURVA,CAJAS,80607695,CFR CAJERO 5X2,PART TIME,1.533333,0.000000,1.533333,0.0,202603
68814,CFR PVEA CHIMBOTE,CAJAS,80608408,CFR CAJERO 3X4,PART TIME,0.000000,0.000000,0.000000,0.0,202603
68815,CFR SVEA SALAMANCA,SALA,80615260,CFR REPRES. DE SERVICIOS,EMPLEADO,4.600000,5.466667,0.000000,0.0,202603